### ISSUE TITLE
Any recommendation for non-paired t-test

### ISSUE THREAD

**Issue by neuromechanist** [jonathanvanleeuwen/SMART#1]
Hi,

I am trying to use your toolbox for my study comparing motor behavior between young and older adults. However, it seems that SMART only accommodates paired t-test. Do you have any suggestions on modifying two-sample functions?

**Comment by jonathanvanleeuwen** [comment]
Unfortunately, I am no longer working at the University and am therefore no longer actively supporting or developing this code any further.

However, I do believe that my co-author wrote some code for other statistical tests. You could email him and ask if he still has it lying around somewhere. 
I have emailed you (the email which is visible in your GitHub account) this response as well as my co-authors contact information. 

I hope this helps.

**Comment by artembelopolsky** [comment]
The weighted t-test for independent samples has been added to SMART_func.py:  https://github.com/jonathanvanleeuwen/SMART/commit/d2bbf6a07dcc42ff0dfbba42332cec01f92bd7e0
